export type ThemeColours = {
  background: string;
  heading: string;
  bodyText: string;
  articleCountText: string;
  highlightText: string;
  highlightBackground: string;
  primaryCta: { text: string; background: string; border?: string | null };
  secondaryCta: { text: string; background: string; border?: string | null };
  closeButton: { text: string; background: string; border?: string | null };
  ticker: {
    filledProgress: string;
    progressBarBackground: string;
    headlineColour: string;
    totalColour: string;
    goalColour: string;
  };
  choiceCards: {
    buttonColour: string;
    buttonTextColour: string;
    buttonBorderColour: string;
    buttonSelectColour: string;
    buttonSelectTextColour: string;
    buttonSelectBorderColour: string;
    buttonSelectMarkerColour: string;
    pillTextColour: string;
    pillBackgroundColour: string;
  };
  logo: string;
};

export type ThemeDefinition = {
  id: string;
  label: string;
  kind: 'Image' | 'ChoiceCards';
  colours: ThemeColours;
};

export type ThemeStyle = {
  id: string;
  label: string;
  themes: ThemeDefinition[];
};

export const colourThemes: { styles: ThemeStyle[] } = {
  styles: [
    {
      id: 'business-as-usual',
      label: 'Business as usual',
      themes: [
        {
          id: 'support-default',
          label: 'Support, Default',
          kind: 'ChoiceCards',
          colours: {
            background: '#F1F8FC',
            heading: '#052962',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#052962',
            highlightBackground: '#FFE500',
            primaryCta: { text: '#052962', background: '#FFE500', border: null },
            secondaryCta: { text: '#000000', background: '#F1F8FC', border: '#000000' },
            closeButton: { text: '#000000', background: '#E6ECEF', border: '#E6ECEF' },
            ticker: {
              filledProgress: '#052962',
              progressBarBackground: '#D4DFE9',
              headlineColour: '#052962',
              totalColour: '#052962',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#F1F8FC',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#FFFFFF',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#052962',
              buttonSelectMarkerColour: '#052962',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#0077B6',
            },
            logo: '#000000',
          },
        },
        {
          id: 'support-default-image',
          label: 'Support, Default (Image)',
          kind: 'Image',
          colours: {
            background: '#F1F8FC',
            heading: '#052962',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#052962',
            highlightBackground: '#FFE500',
            primaryCta: { text: '#052962', background: '#FFE500', border: null },
            secondaryCta: { text: '#000000', background: '#F1F8FC', border: '#000000' },
            closeButton: { text: '#000000', background: '#E6ECEF', border: '#E6ECEF' },
            ticker: {
              filledProgress: '#052962',
              progressBarBackground: '#D4DFE9',
              headlineColour: '#052962',
              totalColour: '#052962',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#F1F8FC',
              buttonTextColour: '#000000',
              buttonBorderColour: '#707070',
              buttonSelectColour: '#FFFFFF',
              buttonSelectTextColour: '#052962',
              buttonSelectBorderColour: '#052962',
              buttonSelectMarkerColour: '#0077B6',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#0077B6',
            },
            logo: '#000000',
          },
        },
        {
          id: 'support-bold',
          label: 'Support, Bold',
          kind: 'ChoiceCards',
          colours: {
            background: '#FFE500',
            heading: '#000000',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#052962',
            primaryCta: { text: '#FFFFFF', background: '#052962', border: null },
            secondaryCta: { text: '#000000', background: '#FFE500', border: '#000000' },
            closeButton: { text: '#000000', background: '#F2DA01', border: '#F2DA01' },
            ticker: {
              filledProgress: '#052962',
              progressBarBackground: '#CDBF14',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#FFE500',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#F1F8FC',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#052962',
              buttonSelectMarkerColour: '#052962',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#052962',
            },
            logo: '#000000',
          },
        },
        {
          id: 'support-bold-image',
          label: 'Support, Bold (Image)',
          kind: 'Image',
          colours: {
            background: '#FFE500',
            heading: '#000000',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#052962',
            primaryCta: { text: '#FFFFFF', background: '#052962', border: null },
            secondaryCta: { text: '#000000', background: '#FFE500', border: '#000000' },
            closeButton: { text: '#000000', background: '#F2DA01', border: '#F2DA01' },
            ticker: {
              filledProgress: '#052962',
              progressBarBackground: '#CDBF14',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#FFE500',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#F1F8FC',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#052962',
              buttonSelectMarkerColour: '#052962',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#052962',
            },
            logo: '#000000',
          },
        },
        {
          id: 'hope-default',
          label: 'Hope, Default',
          kind: 'ChoiceCards',
          colours: {
            background: '#F6F6F6',
            heading: '#0077B6',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#000000',
            highlightBackground: '#90DCFF',
            primaryCta: { text: '#000000', background: '#90DCFF', border: null },
            secondaryCta: { text: '#000000', background: '#F6F6F6', border: '#000000' },
            closeButton: { text: '#000000', background: '#EAEAEA', border: '#EAEAEA' },
            ticker: {
              filledProgress: '#0077B6',
              progressBarBackground: '#B8D6E6',
              headlineColour: '#0077B6',
              totalColour: '#0077B6',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#F6F6F6',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#FDFDFD',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#0077B6',
              buttonSelectMarkerColour: '#005689',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#005689',
            },
            logo: '#000000',
          },
        },
        {
          id: 'hope-default-image',
          label: 'Hope, Default (Image)',
          kind: 'Image',
          colours: {
            background: '#0077B6',
            heading: '#FFFFFF',
            bodyText: '#FFFFFF',
            articleCountText: '#FFFFFF',
            highlightText: '#000000',
            highlightBackground: '#90DCFF',
            primaryCta: { text: '#000000', background: '#90DCFF', border: null },
            secondaryCta: { text: '#FFFFFF', background: '#0077B6', border: '#FFFFFF' },
            closeButton: { text: '#FFFFFF', background: '#0F7EBA', border: '#0F7EBA' },
            ticker: {
              filledProgress: '#90DCFF',
              progressBarBackground: '#329AD0',
              headlineColour: '#FFFFFF',
              totalColour: '#FFFFFF',
              goalColour: '#FFFFFF',
            },
            choiceCards: {
              buttonColour: '#0077B6',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#EDEDED',
              buttonSelectColour: '#D8F1FF',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#005689',
              buttonSelectMarkerColour: '#005689',
              pillTextColour: '#000000',
              pillBackgroundColour: '#00B2FF',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'hope-gentle',
          label: 'Hope, Gentle',
          kind: 'ChoiceCards',
          colours: {
            background: '#90DCFF',
            heading: '#000000',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#0077B6',
            primaryCta: { text: '#FFFFFF', background: '#0077B6', border: null },
            secondaryCta: { text: '#000000', background: '#90DCFF', border: '#000000' },
            closeButton: { text: '#000000', background: '#89D1F2', border: '#89D1F2' },
            ticker: {
              filledProgress: '#0077B6',
              progressBarBackground: '#5EB9E5',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#90DCFF',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#D8F1FF',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#000000',
              buttonSelectMarkerColour: '#000000',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#0077B6',
            },
            logo: '#000000',
          },
        },
        {
          id: 'hope-gentle-image',
          label: 'Hope, Gentle (Image)',
          kind: 'Image',
          colours: {
            background: '#90DCFF',
            heading: '#000000',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#0077B6',
            primaryCta: { text: '#FFFFFF', background: '#0077B6', border: null },
            secondaryCta: { text: '#000000', background: '#90DCFF', border: '#000000' },
            closeButton: { text: '#000000', background: '#89D1F2', border: '#89D1F2' },
            ticker: {
              filledProgress: '#0077B6',
              progressBarBackground: '#5EB9E5',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#90DCFF',
              buttonTextColour: '#000000',
              buttonBorderColour: '#707070',
              buttonSelectColour: '#D8F1FF',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#000000',
              buttonSelectMarkerColour: '#0077B6',
              pillTextColour: '#F6F6F6',
              pillBackgroundColour: '#0077B6',
            },
            logo: '#000000',
          },
        },
        {
          id: 'hope-bold',
          label: 'Hope, Bold',
          kind: 'ChoiceCards',
          colours: {
            background: '#0077B6',
            heading: '#FFFFFF',
            bodyText: '#FFFFFF',
            articleCountText: '#FFFFFF',
            highlightText: '#000000',
            highlightBackground: '#D8F1FF',
            primaryCta: { text: '#000000', background: '#90DCFF', border: null },
            secondaryCta: { text: '#FFFFFF', background: '#0077B6', border: '#FFFFFF' },
            closeButton: { text: '#F6F6F6', background: '#0171AD', border: '#0171AD' },
            ticker: {
              filledProgress: '#90DCFF',
              progressBarBackground: '#329AD0',
              headlineColour: '#FFFFFF',
              totalColour: '#FFFFFF',
              goalColour: '#FFFFFF',
            },
            choiceCards: {
              buttonColour: '#0077B6',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#EDEDED',
              buttonSelectColour: '#D8F1FF',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#005689',
              buttonSelectMarkerColour: '#005689',
              pillTextColour: '#000000',
              pillBackgroundColour: '#00B2FF',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'urgency',
          label: 'Urgency, Default',
          kind: 'ChoiceCards',
          colours: {
            background: '#F6F6F6',
            heading: '#C70000',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#000000',
            highlightBackground: '#FFE500',
            primaryCta: { text: '#000000', background: '#FFE500', border: null },
            secondaryCta: { text: '#000000', background: '#F6F6F6', border: '#000000' },
            closeButton: { text: '#000000', background: '#EAEAEA', border: '#EAEAEA' },
            ticker: {
              filledProgress: '#C70000',
              progressBarBackground: '#EDC5C5',
              headlineColour: '#C70000',
              totalColour: '#C70000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#F6F6F6',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#FFFFFF',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#C70000',
              buttonSelectMarkerColour: '#8B0000',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#8B0000',
            },
            logo: '#000000',
          },
        },
        {
          id: 'urgency-default-image',
          label: 'Urgency, Default (Image)',
          kind: 'Image',
          colours: {
            background: '#AB0613',
            heading: '#FFFFFF',
            bodyText: '#FFFFFF',
            articleCountText: '#FFFFFF',
            highlightText: '#FFFFFF',
            highlightBackground: '#660505',
            primaryCta: { text: '#FFFFFF', background: '#660505', border: null },
            secondaryCta: { text: '#FFFFFF', background: '#AB0613', border: '#FFFFFF' },
            closeButton: { text: '#FFFFFF', background: '#AF121F', border: '#AF121F' },
            ticker: {
              filledProgress: '#FF5943',
              progressBarBackground: '#BC171D',
              headlineColour: '#FFFFFF',
              totalColour: '#FFFFFF',
              goalColour: '#FFFFFF',
            },
            choiceCards: {
              buttonColour: '#F6F6F6',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#FFFFFF',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#C70000',
              buttonSelectMarkerColour: '#8B0000',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#8B0000',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'urgency-bold',
          label: 'Urgency, Bold',
          kind: 'ChoiceCards',
          colours: {
            background: '#AB0613',
            heading: '#FFFFFF',
            bodyText: '#FFFFFF',
            articleCountText: '#FFFFFF',
            highlightText: '#000000',
            highlightBackground: '#FFD8D1',
            primaryCta: { text: '#000000', background: '#FFE500', border: null },
            secondaryCta: { text: '#FFFFFF', background: '#AB0613', border: '#FFFFFF' },
            closeButton: { text: '#FFFFFF', background: '#A30511', border: '#A30511' },
            ticker: {
              filledProgress: '#FF5943',
              progressBarBackground: '#BC171D',
              headlineColour: '#FFFFFF',
              totalColour: '#FFFFFF',
              goalColour: '#FFFFFF',
            },
            choiceCards: {
              buttonColour: '#AB0613',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#EDEDED',
              buttonSelectColour: '#FFD8D1',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#8B0000',
              buttonSelectMarkerColour: '#8B0000',
              pillTextColour: '#000000',
              pillBackgroundColour: '#FF5943',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'empowerment',
          label: 'Empowerment, Default',
          kind: 'ChoiceCards',
          colours: {
            background: '#F6F6F6',
            heading: '#BB3B80',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#000000',
            highlightBackground: '#FFE500',
            primaryCta: { text: '#000000', background: '#FFE500', border: null },
            secondaryCta: { text: '#000000', background: '#F6F6F6', border: '#000000' },
            closeButton: { text: '#000000', background: '#EAEAEA', border: '#EAEAEA' },
            ticker: {
              filledProgress: '#BB3B80',
              progressBarBackground: '#E7C7D9',
              headlineColour: '#000000',
              totalColour: '#BB3B80',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#F6F6F6',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#FDFDFD',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#BB3B80',
              buttonSelectMarkerColour: '#7D0068',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#7D0068',
            },
            logo: '#000000',
          },
        },
        {
          id: 'empowerment-default-image',
          label: 'Empowerment, Default (Image)',
          kind: 'Image',
          colours: {
            background: '#BB3B80',
            heading: '#FFFFFF',
            bodyText: '#FFFFFF',
            articleCountText: '#FFFFFF',
            highlightText: '#FFFFFF',
            highlightBackground: '#7D0068',
            primaryCta: { text: '#FFFFFF', background: '#7D0068', border: null },
            secondaryCta: { text: '#FFFFFF', background: '#BB3B80', border: '#FFFFFF' },
            closeButton: { text: '#FFFFFF', background: '#BE4586', border: '#BE4586' },
            ticker: {
              filledProgress: '#510043',
              progressBarBackground: '#AB2C7A',
              headlineColour: '#FFFFFF',
              totalColour: '#FFFFFF',
              goalColour: '#FFFFFF',
            },
            choiceCards: {
              buttonColour: '#BB3B80',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#EDEDED',
              buttonSelectColour: '#FEF1F8',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#650054',
              buttonSelectMarkerColour: '#650054',
              pillTextColour: '#000000',
              pillBackgroundColour: '#F37ABC',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'empowerment-bold',
          label: 'Empowerment, Bold',
          kind: 'ChoiceCards',
          colours: {
            background: '#BB3B80',
            heading: '#FFFFFF',
            bodyText: '#FFFFFF',
            articleCountText: '#FFFFFF',
            highlightText: '#000000',
            highlightBackground: '#FEF1F8',
            primaryCta: { text: '#000000', background: '#FFE500', border: null },
            secondaryCta: { text: '#FFFFFF', background: '#BB3B80', border: '#FFFFFF' },
            closeButton: { text: '#FFFFFF', background: '#BE4586', border: '#BE4586' },
            ticker: {
              filledProgress: '#510043',
              progressBarBackground: '#AB2C7A',
              headlineColour: '#FFFFFF',
              totalColour: '#FFFFFF',
              goalColour: '#FFFFFF',
            },
            choiceCards: {
              buttonColour: '#BB3B80',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#EDEDED',
              buttonSelectColour: '#FEF1F8',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#650054',
              buttonSelectMarkerColour: '#650054',
              pillTextColour: '#000000',
              pillBackgroundColour: '#F37ABC',
            },
            logo: '#FFFFFF',
          },
        },
      ],
    },
    {
      id: 'feast-marketing',
      label: 'Feast Marketing',
      themes: [
        {
          id: 'light-turmeric-default',
          label: 'Light Turmeric, Default (Image)',
          kind: 'Image',
          colours: {
            background: '#FFF1D7',
            heading: '#20201D',
            bodyText: '#20201D',
            articleCountText: '#20201D',
            highlightText: '#FAFAFA',
            highlightBackground: '#A36000',
            primaryCta: { text: '#FAFAFA', background: '#A36000', border: null },
            secondaryCta: { text: '#20201D', background: '#FFF1D7', border: '#20201D' },
            closeButton: { text: '#000000', background: '#F2E5CC', border: '#F2E5CC' },
            ticker: {
              filledProgress: '#A36000',
              progressBarBackground: '#FAFAFA',
              headlineColour: '#20201D',
              totalColour: '#20201D',
              goalColour: '#20201D',
            },
            choiceCards: {
              buttonColour: '#FFF1D7',
              buttonTextColour: '#20201D',
              buttonBorderColour: '#20201D',
              buttonSelectColour: '#FAFAFA',
              buttonSelectTextColour: '#20201D',
              buttonSelectBorderColour: '#A36000',
              buttonSelectMarkerColour: '#A36000',
              pillTextColour: '#FAFAFA',
              pillBackgroundColour: '#A36000',
            },
            logo: '#000000',
          },
        },
        {
          id: 'light-turmeric-basil',
          label: 'Light Turmeric, Basil (Image)',
          kind: 'Image',
          colours: {
            background: '#FFF1D7',
            heading: '#20201D',
            bodyText: '#20201D',
            articleCountText: '#20201D',
            highlightText: '#20201D',
            highlightBackground: '#879F84',
            primaryCta: { text: '#20201D', background: '#879F84', border: null },
            secondaryCta: { text: '#20201D', background: '#FFF1D7', border: '#20201D' },
            closeButton: { text: '#000000', background: '#F2E5CC', border: '#F2E5CC' },
            ticker: {
              filledProgress: '#879F84',
              progressBarBackground: '#FAFAFA',
              headlineColour: '#20201D',
              totalColour: '#20201D',
              goalColour: '#20201D',
            },
            choiceCards: {
              buttonColour: '#FFF1D7',
              buttonTextColour: '#20201D',
              buttonBorderColour: '#20201D',
              buttonSelectColour: '#FAFAFA',
              buttonSelectTextColour: '#20201D',
              buttonSelectBorderColour: '#879F84',
              buttonSelectMarkerColour: '#879F84',
              pillTextColour: '#20201D',
              pillBackgroundColour: '#879F84',
            },
            logo: '#000000',
          },
        },
        {
          id: 'light-turmeric-blueberry',
          label: 'Light Turmeric, Blueberry (Image)',
          kind: 'Image',
          colours: {
            background: '#FFF1D7',
            heading: '#20201D',
            bodyText: '#20201D',
            articleCountText: '#20201D',
            highlightText: '#FAFAFA',
            highlightBackground: '#20809E',
            primaryCta: { text: '#FAFAFA', background: '#20809E', border: null },
            secondaryCta: { text: '#20201D', background: '#FFF1D7', border: '#20201D' },
            closeButton: { text: '#000000', background: '#F2E5CC', border: '#F2E5CC' },
            ticker: {
              filledProgress: '#20809E',
              progressBarBackground: '#FAFAFA',
              headlineColour: '#20201D',
              totalColour: '#20201D',
              goalColour: '#20201D',
            },
            choiceCards: {
              buttonColour: '#FFF1D7',
              buttonTextColour: '#20201D',
              buttonBorderColour: '#20201D',
              buttonSelectColour: '#FAFAFA',
              buttonSelectTextColour: '#20201D',
              buttonSelectBorderColour: '#20809E',
              buttonSelectMarkerColour: '#20809E',
              pillTextColour: '#FAFAFA',
              pillBackgroundColour: '#20809E',
            },
            logo: '#000000',
          },
        },
        {
          id: 'light-paprika-default',
          label: 'Light Paprika, Default (Image)',
          kind: 'Image',
          colours: {
            background: '#F7EFE9',
            heading: '#20201D',
            bodyText: '#20201D',
            articleCountText: '#20201D',
            highlightText: '#20201D',
            highlightBackground: '#F56900',
            primaryCta: { text: '#20201D', background: '#F56900', border: null },
            secondaryCta: { text: '#20201D', background: '#F7EFE9', border: '#20201D' },
            closeButton: { text: '#000000', background: '#EBE4DD', border: '#EBE4DD' },
            ticker: {
              filledProgress: '#F56900',
              progressBarBackground: '#FAFAFA',
              headlineColour: '#20201D',
              totalColour: '#20201D',
              goalColour: '#20201D',
            },
            choiceCards: {
              buttonColour: '#F7EFE9',
              buttonTextColour: '#20201D',
              buttonBorderColour: '#20201D',
              buttonSelectColour: '#FAFAFA',
              buttonSelectTextColour: '#20201D',
              buttonSelectBorderColour: '#F56900',
              buttonSelectMarkerColour: '#F56900',
              pillTextColour: '#FAFAFA',
              pillBackgroundColour: '#F56900',
            },
            logo: '#000000',
          },
        },
        {
          id: 'light-paprika-kaffir-a',
          label: 'Light Paprika, Kaffir A (Image)',
          kind: 'Image',
          colours: {
            background: '#F7EFE9',
            heading: '#20201D',
            bodyText: '#20201D',
            articleCountText: '#20201D',
            highlightText: '#20201D',
            highlightBackground: '#BED01E',
            primaryCta: { text: '#20201D', background: '#BED01E', border: null },
            secondaryCta: { text: '#20201D', background: '#F7EFE9', border: '#20201D' },
            closeButton: { text: '#000000', background: '#EBE4DD', border: '#EBE4DD' },
            ticker: {
              filledProgress: '#BED01E',
              progressBarBackground: '#FAFAFA',
              headlineColour: '#20201D',
              totalColour: '#20201D',
              goalColour: '#20201D',
            },
            choiceCards: {
              buttonColour: '#F7EFE9',
              buttonTextColour: '#20201D',
              buttonBorderColour: '#20201D',
              buttonSelectColour: '#FAFAFA',
              buttonSelectTextColour: '#20201D',
              buttonSelectBorderColour: '#BED01E',
              buttonSelectMarkerColour: '#BED01E',
              pillTextColour: '#20201D',
              pillBackgroundColour: '#BED01E',
            },
            logo: '#000000',
          },
        },
        {
          id: 'light-paprika-kaffir-b',
          label: 'Light Paprika, Kaffir B (Image)',
          kind: 'Image',
          colours: {
            background: '#F7EFE9',
            heading: '#20201D',
            bodyText: '#20201D',
            articleCountText: '#20201D',
            highlightText: '#FAFAFA',
            highlightBackground: '#697311',
            primaryCta: { text: '#FAFAFA', background: '#697311', border: null },
            secondaryCta: { text: '#20201D', background: '#F7EFE9', border: '#20201D' },
            closeButton: { text: '#000000', background: '#EBE4DD', border: '#EBE4DD' },
            ticker: {
              filledProgress: '#697311',
              progressBarBackground: '#FAFAFA',
              headlineColour: '#20201D',
              totalColour: '#20201D',
              goalColour: '#20201D',
            },
            choiceCards: {
              buttonColour: '#F7EFE9',
              buttonTextColour: '#20201D',
              buttonBorderColour: '#20201D',
              buttonSelectColour: '#FAFAFA',
              buttonSelectTextColour: '#20201D',
              buttonSelectBorderColour: '#697311',
              buttonSelectMarkerColour: '#697311',
              pillTextColour: '#FAFAFA',
              pillBackgroundColour: '#697311',
            },
            logo: '#000000',
          },
        },
      ],
    },
    {
      id: 'guardian-weekly',
      label: 'Guardian Weekly',
      themes: [
        {
          id: 'guardian-weekly-dark-image',
          label: 'Dark, Image',
          kind: 'Image',
          colours: {
            background: '#222527',
            heading: '#F6F6F6',
            bodyText: '#F6F6F6',
            articleCountText: '#F6F6F6',
            highlightText: '#000000',
            highlightBackground: '#FFD900',
            primaryCta: { text: '#000000', background: '#FFD900', border: null },
            secondaryCta: { text: '#F6F6F6', background: '#222527', border: '#F6F6F6' },
            closeButton: { text: '#FFFFFF', background: '#2D3032', border: '#2D3032' },
            ticker: {
              filledProgress: '#F6F6F6',
              progressBarBackground: '#4B4F52',
              headlineColour: '#F6F6F6',
              totalColour: '#F6F6F6',
              goalColour: '#F6F6F6',
            },
            choiceCards: {
              buttonColour: '#222527',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#F6F6F6',
              buttonSelectColour: '#F6F6F6',
              buttonSelectTextColour: '#4B4F52',
              buttonSelectBorderColour: '#4B4F52',
              buttonSelectMarkerColour: '#FFD900',
              pillTextColour: '#000000',
              pillBackgroundColour: '#FFD900',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'guardian-weekly-light-image',
          label: 'Light, Image',
          kind: 'Image',
          colours: {
            background: '#F6F6F6',
            heading: '#052962',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#000000',
            highlightBackground: '#FFE500',
            primaryCta: { text: '#000000', background: '#FFE500', border: null },
            secondaryCta: { text: '#000000', background: '#F6F6F6', border: '#000000' },
            closeButton: { text: '#000000', background: '#EAEAEA', border: '#EAEAEA' },
            ticker: {
              filledProgress: '#000000',
              progressBarBackground: '#FFE500',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#F6F6F6',
              buttonTextColour: '#000000',
              buttonBorderColour: '#707070',
              buttonSelectColour: '#F5F6F7',
              buttonSelectTextColour: '#4B4F52',
              buttonSelectBorderColour: '#000000',
              buttonSelectMarkerColour: '#FFE500',
              pillTextColour: '#000000',
              pillBackgroundColour: '#FFE500',
            },
            logo: '#000000',
          },
        },
        {
          id: 'guardian-weekly-brand-image',
          label: 'Brand, Image',
          kind: 'Image',
          colours: {
            background: '#0077B6',
            heading: '#FFFFFF',
            bodyText: '#FFFFFF',
            articleCountText: '#FFFFFF',
            highlightText: '#FFFFFF',
            highlightBackground: '#052962',
            primaryCta: { text: '#FFFFFF', background: '#052962', border: null },
            secondaryCta: { text: '#FFFFFF', background: '#0077B6', border: '#FFFFFF' },
            closeButton: { text: '#FFFFFF', background: '#0F7EBA', border: '#0F7EBA' },
            ticker: {
              filledProgress: '#FFFFFF',
              progressBarBackground: '#2F91C4',
              headlineColour: '#FFFFFF',
              totalColour: '#FFFFFF',
              goalColour: '#FFFFFF',
            },
            choiceCards: {
              buttonColour: '#0077B6',
              buttonTextColour: '#FFFFFF',
              buttonBorderColour: '#FFFFFF',
              buttonSelectColour: '#FFFFFF',
              buttonSelectTextColour: '#052962',
              buttonSelectBorderColour: '#052962',
              buttonSelectMarkerColour: '#052962',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#052962',
            },
            logo: '#FFFFFF',
          },
        },
      ],
    },
    {
      id: 'marketing',
      label: 'Marketing',
      themes: [
        {
          id: 'marketing-labs',
          label: 'Marketing, Labs',
          kind: 'ChoiceCards',
          colours: {
            background: '#65A897',
            heading: '#650054',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#650054',
            primaryCta: { text: '#FFFFFF', background: '#650054', border: null },
            secondaryCta: { text: '#000000', background: '#65A897', border: '#000000' },
            closeButton: { text: '#000000', background: '#60A08F', border: '#60A08F' },
            ticker: {
              filledProgress: '#650054',
              progressBarBackground: '#65868A',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#65A897',
              buttonTextColour: '#000000',
              buttonBorderColour: '#333333',
              buttonSelectColour: '#DCF4F3',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#650054',
              buttonSelectMarkerColour: '#650054',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#BB3B80',
            },
            logo: '#000000',
          },
        },
        {
          id: 'marketing-labs-image',
          label: 'Marketing, Labs (Image)',
          kind: 'Image',
          colours: {
            background: '#65A897',
            heading: '#650054',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#650054',
            primaryCta: { text: '#FFFFFF', background: '#650054', border: null },
            secondaryCta: { text: '#000000', background: '#65A897', border: '#000000' },
            closeButton: { text: '#000000', background: '#60A08F', border: '#60A08F' },
            ticker: {
              filledProgress: '#650054',
              progressBarBackground: '#65868A',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#65A897',
              buttonTextColour: '#000000',
              buttonBorderColour: '#333333',
              buttonSelectColour: '#DCF4F3',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#650054',
              buttonSelectMarkerColour: '#650054',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#BB3B80',
            },
            logo: '#000000',
          },
        },
        {
          id: 'marketing-opinion',
          label: 'Marketing, Opinion',
          kind: 'ChoiceCards',
          colours: {
            background: '#FF9941',
            heading: '#09615B',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#000000',
            highlightBackground: '#FFE7D4',
            primaryCta: { text: '#000000', background: '#FFE7D4', border: null },
            secondaryCta: { text: '#000000', background: '#FF9941', border: '#000000' },
            closeButton: { text: '#000000', background: '#F2913E', border: '#F2913E' },
            ticker: {
              filledProgress: '#FFE7D4',
              progressBarBackground: '#FFB474',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#FF9941',
              buttonTextColour: '#000000',
              buttonBorderColour: '#333333',
              buttonSelectColour: '#FFE7D4',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#09615B',
              buttonSelectMarkerColour: '#09615B',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#E05E00',
            },
            logo: '#000000',
          },
        },
        {
          id: 'marketing-opinion-image',
          label: 'Marketing, Opinion (Image)',
          kind: 'Image',
          colours: {
            background: '#FF9941',
            heading: '#09615B',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#000000',
            highlightBackground: '#FFE7D4',
            primaryCta: { text: '#000000', background: '#FFE7D4', border: null },
            secondaryCta: { text: '#000000', background: '#FF9941', border: '#000000' },
            closeButton: { text: '#000000', background: '#F2913E', border: '#F2913E' },
            ticker: {
              filledProgress: '#FFE7D4',
              progressBarBackground: '#FFB474',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#FF9941',
              buttonTextColour: '#000000',
              buttonBorderColour: '#333333',
              buttonSelectColour: '#FFE7D4',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#09615B',
              buttonSelectMarkerColour: '#09615B',
              pillTextColour: '#FFFFFF',
              pillBackgroundColour: '#E05E00',
            },
            logo: '#000000',
          },
        },
        {
          id: 'marketing-lifestyle',
          label: 'Marketing, Lifestyle',
          kind: 'ChoiceCards',
          colours: {
            background: '#7D0068',
            heading: '#FF9941',
            bodyText: '#F6F6F6',
            articleCountText: '#F6F6F6',
            highlightText: '#000000',
            highlightBackground: '#FF9941',
            primaryCta: { text: '#000000', background: '#FF9941', border: null },
            secondaryCta: { text: '#F6F6F6', background: '#7D0068', border: '#F6F6F6' },
            closeButton: { text: '#F6F6F6', background: '#830E70', border: '#830E70' },
            ticker: {
              filledProgress: '#FF9941',
              progressBarBackground: '#AA365A',
              headlineColour: '#F6F6F6',
              totalColour: '#F6F6F6',
              goalColour: '#F6F6F6',
            },
            choiceCards: {
              buttonColour: '#7D0068',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#EDEDED',
              buttonSelectColour: '#FEF1F8',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#510043',
              buttonSelectMarkerColour: '#510043',
              pillTextColour: '#000000',
              pillBackgroundColour: '#FFABDB',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'marketing-lifestyle-image',
          label: 'Marketing, Lifestyle (Image)',
          kind: 'Image',
          colours: {
            background: '#7D0068',
            heading: '#FF9941',
            bodyText: '#F6F6F6',
            articleCountText: '#F6F6F6',
            highlightText: '#000000',
            highlightBackground: '#FF9941',
            primaryCta: { text: '#000000', background: '#FF9941', border: null },
            secondaryCta: { text: '#F6F6F6', background: '#7D0068', border: '#F6F6F6' },
            closeButton: { text: '#F6F6F6', background: '#830E70', border: '#830E70' },
            ticker: {
              filledProgress: '#FF9941',
              progressBarBackground: '#AA365A',
              headlineColour: '#F6F6F6',
              totalColour: '#F6F6F6',
              goalColour: '#F6F6F6',
            },
            choiceCards: {
              buttonColour: '#7D0068',
              buttonTextColour: '#F6F6F6',
              buttonBorderColour: '#EDEDED',
              buttonSelectColour: '#FEF1F8',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#510043',
              buttonSelectMarkerColour: '#510043',
              pillTextColour: '#000000',
              pillBackgroundColour: '#FFABDB',
            },
            logo: '#FFFFFF',
          },
        },
        {
          id: 'marketing-labs-light',
          label: 'Marketing, Labs Light',
          kind: 'ChoiceCards',
          colours: {
            background: '#A8E3DF',
            heading: '#510043',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#510043',
            primaryCta: { text: '#FFFFFF', background: '#510043', border: null },
            secondaryCta: { text: '#000000', background: '#A8E3DF', border: '#000000' },
            closeButton: { text: '#000000', background: '#A0D8D4', border: '#A0D8D4' },
            ticker: {
              filledProgress: '#510043',
              progressBarBackground: '#97B6C0',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#A8E3DF',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#F3FBFB',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#510043',
              buttonSelectMarkerColour: '#510043',
              pillTextColour: '#000000',
              pillBackgroundColour: '#65A897',
            },
            logo: '#000000',
          },
        },
        {
          id: 'marketing-labs-light-image',
          label: 'Marketing, Labs Light (Image)',
          kind: 'Image',
          colours: {
            background: '#A8E3DF',
            heading: '#510043',
            bodyText: '#000000',
            articleCountText: '#000000',
            highlightText: '#FFFFFF',
            highlightBackground: '#510043',
            primaryCta: { text: '#FFFFFF', background: '#510043', border: null },
            secondaryCta: { text: '#000000', background: '#A8E3DF', border: '#000000' },
            closeButton: { text: '#000000', background: '#A0D8D4', border: '#A0D8D4' },
            ticker: {
              filledProgress: '#510043',
              progressBarBackground: '#97B6C0',
              headlineColour: '#000000',
              totalColour: '#000000',
              goalColour: '#000000',
            },
            choiceCards: {
              buttonColour: '#A8E3DF',
              buttonTextColour: '#000000',
              buttonBorderColour: '#545454',
              buttonSelectColour: '#F3FBFB',
              buttonSelectTextColour: '#000000',
              buttonSelectBorderColour: '#510043',
              buttonSelectMarkerColour: '#510043',
              pillTextColour: '#000000',
              pillBackgroundColour: '#65A897',
            },
            logo: '#000000',
          },
        },
      ],
    },
  ],
};
