#!/bin/bash

# Exit if any of these commands fail
set -e

export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install
nvm use

npm install
npm list
npm run lint
npm run test
npm run build

